spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cvhz8rzfqnup.ap-northeast-2.rds.amazonaws.com:3306/isthereopen?serverTimezone=Asia/Seoul
    username: flavorsoojung
    password: ogonge^^
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none #validate
        format_sql: true
    hibernate:
      ddl-auto: none
    #  use-new-id-generator-mappings: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE